spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379